# -*- coding: utf-8 -*-
"""Task6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17yoGe8mDrqK0TMAIFk0HBj3IkHJpac1a

## Task 6

### Arrays
"""

import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    return(numpy.array(arr[::-1], float))
   
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

"""### Shape and Reshape"""

import numpy
print(numpy.array(input().split(),int).reshape(3, 3))

"""### Transpose and flatten"""

import numpy
n, m = map(int, input().split())

res= numpy.array([input().strip().split() for _ in range(n)], int)
print (res.transpose())
print (res.flatten())

"""### Concatenate"""

import numpy
n1, N, M = map(int,input().split())
A = numpy.array([input().split() for _ in range(n1)],int)
B = numpy.array([input().split() for _ in range(N)],int)
print(numpy.concatenate((A, B), axis = 0))

"""### Zeros and Ones"""

import numpy
N = tuple(map(int, input().split()))
print(numpy.zeros(N, int))
print(numpy.ones(N, int))

"""### Eyes and Identity"""

import numpy
numpy.set_printoptions(sign=' ')
print(numpy.eye(*map(int, input().split())))

"""### Array Mathematics"""

import numpy
N, M = map(int, input().split())

A = numpy.array([list(map(int, input().split())) for n in range(N)])
B = numpy.array([list(map(int, input().split())) for n in range(N)])

print(A + B)
print(A - B)
print(A * B)
print(A // B)
print(A % B)
print(A ** B)

"""### Floor Ceil and Rint"""

import numpy
numpy.set_printoptions(sign=' ')

arr = numpy.array(input().split(),float)

print(numpy.floor(arr))
print(numpy.ceil(arr))
print(numpy.rint(arr))

"""### Sum and Prod"""

N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)], int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))

"""### MIn and Max"""

import numpy

N, M = map(int, input().split())
st = numpy.array([input().split() for _ in range(N)],int)
print(numpy.max(numpy.min(st, axis=1), axis=0))

"""### Mean,Var and Std"""

import numpy
n,m=map(int,input().split())
numpy.set_printoptions(legacy='1.10')
a=numpy.array([list(map(int,input().split())) for i in range(n)])

print(numpy.mean(a,axis=1))
print(numpy.var(a,axis=0))
print(numpy.std(a,None))

"""### Dot and Cross"""

import numpy
n = int(input())
a = numpy.array([input().split() for _ in range(n)], int)
b = numpy.array([input().split() for _ in range(n)], int)
print(numpy.dot(a, b))

"""### Inner and outer"""

import numpy
A = numpy.array(input().split(), int)
B = numpy.array(input().split(), int)
print(numpy.inner(A, B), numpy.outer(A, B), sep='\n')

"""### Poly"""

import numpy
poly = [float(x) for x in input().split()]
x = float(input())

print(numpy.polyval(poly, x))

"""### Linear Algebra"""

import numpy
N = int(input())
A = numpy.array([input().split() for _ in range(N)], float)
print(round(numpy.linalg.det(A),2))