# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n5gxIXLXx7xGXKpcUfOJsuJeXdjJG3C5

## Task 1

### Running Sum of 1D array
"""

class Solution:
    def runningSum(self, nums: List[int]) -> List[int]:
        arr=[]
        c=0
        for i in  nums :
            c += i
            arr.append(c)
        return arr

"""### Shuffle The array"""

class Solution:
    def shuffle(self, nums: List[int], n: int) -> List[int]:
        arr=[]
        no=len(nums)
        for i in range(no//2):
            arr.append(nums[i])
            arr.append(nums[i+no//2])
        return arr

"""### Greatest number of candies"""

class Solution:
    def kidsWithCandies(self, candies: List[int], extraCandies: int) -> List[bool]:
        arr=[]
        for candy in candies:
            
            n=candy+extraCandies
            a=True
            for c in candies:
                 if n < c :
                        a=False
            arr.append(a)
        return arr